### ISSUE TITLE
private tags on methods not picked up

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#14]
From _WidgetBase, postscript() has a private tag:

``` javascript
postscript: function(/*Object?*/params, /*DomNode|String*/srcNodeRef){
    // summary:
    //      Kicks off widget instantiation.  See create() for details.
    // tags:
    //      private
    this.create(params, srcNodeRef);
},
```

but it's not picked up:

``` xml
<method name="postscript" scope="prototype" type="function" from="dijit/_WidgetBase">
<parameters>
<parameter name="params" type="Object" usage="optional"/>
<parameter name="srcNodeRef" type="DomNode|String" usage="required"/>
</parameters>
<return-types/>
<summary>
Kicks off widget instantiation. See create() for details.
</summary>
</method>
```

Likewise for other tags, but I filed #20 for that issue since you already closed this ticket.

cc @pruzand

**Comment by csnover** [comment]
Added private tag support in df733f7.

**Comment by wkeese** [comment]
This really shouldn't be closed until you are picking up all the tags.    Maybe the feature doesn't need to be there for 1.8, but clearly from looking at dojo's code base and it's style guide (http://livedocs.dojotoolkit.org/util/doctools/markup#tags) all tags are supposed to work.

Oh hmm, I can't reopen, so I made #20 instead.
