### ISSUE TITLE
problem with path with ../

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#2]
When I run:

$ ./parse.sh ../trunk/dojo

the parser gets confused about paths, leading to an error:

ERR: ../trunk/dojo/_base/array.js:1:41 Error: ENOENT, no such file or directory '../trunk/dojo/trunk/dojo/_base/kernel.js'

Notice how "trunk/dojo" is repeated in the path.

**Comment by csnover** [comment]
This behaviour is expected since you’re trying to access files outside the base path of the parser. If you set `basePath` in config.js to `../trunk/`, it should work correctly.

**Comment by wkeese** [comment]
I tried that, but it doesn't seem to have any effect:

My config file has:

```
// Configuration data for module ID resolution and path remapping within the parser.
// TODO: Document
moduleConfig: {
    basePath: '../trunk/',
    prefixMap: { dojo: 'dojo', dijit: 'dijit' }
}
```

My output is:

mac:docparse bill$ ./parse.sh dijit
debugger listening on port 5858
WARN:  Attempt to get undefined variable "String.prototype"
WARN:  Attempt to get undefined variable "Array.prototype"
WARN:  Attempt to get undefined variable "Function.prototype"
WARN:  Attempt to get undefined variable "Function"
WARN:  Attempt to get undefined variable "Object.prototype"
WARN:  Attempt to get undefined variable "Function.prototype"
WARN:  Attempt to get undefined variable "Function"
WARN:  Attempt to get undefined variable "Object.prototype"
WARN:  Attempt to get undefined variable "Array.prototype"
WARN:  Attempt to get undefined variable "Function.prototype"
WARN:  Attempt to get undefined variable "Function"
WARN:  Attempt to get undefined variable "Function.prototype"
WARN:  Attempt to get undefined variable "Function"
WARN:  Attempt to get undefined variable "Object.prototype"
ERR:  Error: ENOENT, no such file or directory 'dijit'

**Comment by csnover** [comment]
How is it with the latest commit?

**Comment by wkeese** [comment]
Cool, that seems to be working much better.   I'm getting an error on
TimeTextBox but presumably unrelated to this old problem.  Thanks for the
excludePaths enhancement too.

**Comment by aramk** [comment]
Is there any way of preventing an http request from being used as a folder path?

`ERR: earth/Geocoder.js:17:2 Error: ENOENT, no such file or directory '/Users/Aram/Development/Java/MUtopia/Code/mutopia-gui/src/static/https:/www.google.com/jsapi.js'`

My source:

<pre><code>define([
    'dojo/_base/declare',
    'dojo/_base/lang',
    'dojo/request/script',
    'earth/wkt/Extensions',
    // Required
    'https://www.google.com/jsapi'
], function (declare, lang, wkt) {</code></pre>

**Comment by csnover** [comment]
@aramkocharyan You might be able to set http: and https: as exclusions in your config.js. Obviously attempting to read such dependencies as a module is a bug.

**Comment by aramk** [comment]
I tried that and it didn't seem to work, so I went with wrapping the URL in a module itself and then excluding that module.
