### ISSUE TITLE
private tags on variables not picked up

### ISSUE THREAD

**Issue by dmandrioli** [csnover/js-doc-parse#25]
```
    // _radius: Number
    // tags:
    //      private
    _radius: 100,
```

gives

```
<properties>
  <property name="_radius" scope="prototype" type="Number"
  from="dojox/dgauges/components/default/CircularLinearGauge" />
  ...
</properties>
```

**Comment by cjolif** [comment]
see also #13. Not sure what the right syntax is...

**Comment by AdrianVasiliu** [comment]
This syntax works fine for me:

```
// _radius: [private] Number
_radius: 100,
```

(that is, I do get private="true" in the XML for it).

This also works if there is a doc on the property:

```
// _radius: [private] Number
//          This is some doc.
_radius: 100,
```

**Comment by cjolif** [comment]
It seems I have the same issue with classes.

**Comment by csnover** [comment]
`// tags:` is never valid for properties, only for objects.

**Comment by cjolif** [comment]
@csnover What about classes they are objects and it seems it does not work. Do you reproduce ? 
Cc: @wkeese

**Comment by wkeese** [comment]
@cjolif, can you give a code example of what you are talking about?

**Comment by cjolif** [comment]
@wkeese for example dojox/trunk/charting/action2d/_IndicatorElement the class does have a private tag but that is not reflected in the XML (I did not pull the latest updates thought).

**Comment by wkeese** [comment]
Oh... that seems like a separate issue, you should file a separate ticket for that.
