### ISSUE TITLE
kwArgs inlining mechanism does not work if the kwArgs param is optional

### ISSUE THREAD

**Issue by cjolif** [csnover/js-doc-parse#27]
See for example dojox/charting/action2d/Highlight the kwArgs param of the ctor is optional: __XXXCtorArg? and just making it optional breaks the inlining mechanism.

**Comment by csnover** [comment]
Some of the doc blocks in charting are referencing objects that do not exist, so please make sure you fix those or this fix won’t help you. :)

**Comment by cjolif** [comment]
Thanks, well I know that too well as that's exactly what I spending my time on :-(
