### ISSUE TITLE
Make sure the output contains only one full definition for an object

### ISSUE THREAD

**Issue by ttrenka** [csnover/js-doc-parse#28]
The current output of the parser seems to duplicate full object definitions when outputting an XML file; in other words, if more than one module includes the same source object, the entire object's definition seems to be included in the output.

It would be more efficient if the processor looked to see if a module's definition has already been included in the output, and then simply use a self-closing tag to reference it.  For example, if dojo/_base/kernel has already had it's full definition included in an output, any other reference to it would look something like:

`<object location="dojo/_base/kernel" />`

This would reduce the size of the output tremendously.

**Comment by csnover** [comment]
Is this different from #29? If so, how?

**Comment by wkeese** [comment]
I don't understand this ticket either.   The only duplication of "objects" that I know of is of kwargs definitions, and perhaps for modules that return other modules (like how NodeList-data.js returns NodeList).

(In other words, please give a specific example of a duplicated object definition.)

**Comment by ttrenka** [comment]
I'll try to find you an example when I can grab the latest details.xml file.  Mostly this issue is open to keep track of _only_ duplicated objects; its different from #29 in that that ticket is intended to track the masking of fields within an object.

**Comment by ttrenka** [comment]
Just grabbed the latest details.xml from @wkeese and so far not seeing duplicated objects.  I'm going to leave this open for now though; the file I'd examined before was only for Dijit, and I saw dups there (particularly when it came to dependencies from other packages).

**Comment by ttrenka** [comment]
I'm looking at the output for just dijit/form, and it would seem that the duplication I saw two weeks ago is no longer there...so I'm guessing this is no longer relevant. Closing it out.
