### ISSUE TITLE
problem with dojo/main --> ./_base/kernel dependency

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#3]
This is where I got stuck trying to fix up errors in the dojo/ and dijit/ files that trip up the doc parser:

mac:docparse bill$ ./parse.sh dojo/main.js
...
debug:   Resolving dependency ./_base/kernel
debug:   Getting module dojo./_base/kernel
debug:   Module not in cache, retrieving by file
ERR: dojo/main.js:18:2 Error: ENOENT, no such file or directory 'dojo./_base/kernel.js'

(Notice how it's dojo. rather than just dojo)

**Comment by csnover** [comment]
Fixed in de6f994.
