### ISSUE TITLE
Support for code examples in the API doc of properties

### ISSUE THREAD

**Issue by AdrianVasiliu** [csnover/js-doc-parse#31]
Would be nice to be able to include code examples in the API doc of properties, just as for classes or methods. 

For maximum consistency with the way we include examples for classes and methods, the doc of properties may support an "example" section, say:

```
// myProp: Object
//      This is a property.
// example:
// |    an example of usage
myProp: null,
```

Or at least to be able to include code blocks:

```
// myProp: Object
//      This is a property. Here is an example:
// |    an example of usage
myProp: null,
```

The "Dojo Inline Documentation" (http://livedocs.dojotoolkit.org/util/doctools/markup#using-markdown ) also mentions the use of backticks for inline pieces of code, however this does not seem to work in the API doc of properties (tried the sourrounding with one backticks and with three backticks): the XML includes the backticks as-is.

**Comment by csnover** [comment]
The second syntax should already work. The first syntax will never work because example could be the name of the property.

**Comment by AdrianVasiliu** [comment]
I confirm, the second syntax works (tested with the latest js-doc-parse). Great, thanks.

For the first syntax, well, we could imagine avoiding the ambiguity you mention by using a more distinctive name than "example", say "doc-example" or "js-doc-example". Or we could even wonder why the name of the property needs to be repeated in the doc comment and redesign the syntax for doc comments of properties to be more consistent with the one in use for methods. Say:

```
// summary:
//         This is a property.
// type:
//         Number
// example:
//  |      some example
myProp: null,
```

Of course, this is just brainstorming about future evolutions.

**Comment by AdrianVasiliu** [comment]
I confirm, the second syntax works (tested with the latest js-doc-parse). Great, thanks.

For the first syntax, well, we could imagine avoiding the ambiguity you mention by using a more distinctive name than "example", say "doc-example" or "js-doc-example". Or we could even wonder why the name of the property needs to be repeated in the doc comment and redesign the syntax for doc comments of properties to be more consistent with the one in use for methods. Say:

```
// summary:
//         This is a property.
// type:
//         Number
// example:
//  |      some example
myProp: null,
```

Of course, this is just brainstorming about future evolutions.

**Comment by AdrianVasiliu** [comment]
I confirm, the second syntax works (tested with the latest js-doc-parse). Great, thanks.

For the first syntax, well, we could imagine avoiding the ambiguity you mention by using a more distinctive name than "example", say "doc-example" or "js-doc-example". Or we could even wonder why the name of the property needs to be repeated in the doc comment and redesign the syntax for doc comments of properties to be more consistent with the one in use for methods. Say:

```
// summary:
//         This is a property.
// type:
//         Number
// example:
//  |      some example
myProp: null,
```

Of course, this is just brainstorming about future evolutions.
