### ISSUE TITLE
Making the deprecation information visible in the API doc

### ISSUE THREAD

**Issue by AdrianVasiliu** [csnover/js-doc-parse#32]
While the user is able to see the deprecation information in the console at runtime (but not by default...), the information is missing in the API doc. It would be nice to introduce doc tags for this purpose. 
However, a simple "deprecated" tag wouldn't be enough, it would need to be enriched with the deprecation hints (the arguments of dojo/_base/kernel.deprecated).

**Comment by wkeese** [comment]
Note that a lot of code is using

```
// tags:
//     deprecated
```

or

```
// foo: [deprecated] String
```

**Comment by csnover** [comment]
This data is already being put in the XML output where possible. However, 
1. these deprecation warnings often rely on information only available at runtime (like whether or not someone set a property before calling a method)
2. the viewer has no ability to consume this output.

I don’t plan on tracking viewer issues here, at least for now, so I’m going to close this issue since the parser already handles deprecated/experimental calls.

**Comment by AdrianVasiliu** [comment]
Well, concerning the deprecation data "already being put in the XML where possible", this does not seem to hold for these doc comments of properties and methods:

```
// someProp: [deprecated] Number
//      This is a property.
someProp: 1,

someMethod: function(){
        // summary:
        //      Some method.
        // tags:
        //      deprecated
},
```

The generated XML:

```
<property name="someProp" scope="prototype" type="number" from="parserTest/ParserTest">
<summary>&lt;p>This is a property.&lt;/p></summary></property>

<method name="someMethod" scope="prototype" type="function" from="parserTest/ParserTest">
<parameters/><return-types/><summary>&lt;p>Some method.&lt;/p></summary></method>
```

Maybe just https://github.com/csnover/js-doc-parse/issues/13 which hurts here too.

On the other side, even if the "deprecated" tag would make its way into the XML then HTML doc, this would leave aside contextual information (hints about replacement of the deprecated API, version number etc.) which would be useful to include in the API doc. Therefore, in the longer run, I would think we would need dedicated sections in the doc comments.

**Comment by AdrianVasiliu** [comment]
(Of course, waiting for a better solution, the solution would be to write the deprecation information directly in the comment of the property or method.)
