### ISSUE TITLE
variables that have a "standard keys" name break parser

### ISSUE THREAD

**Issue by mbillau** [csnover/js-doc-parse#33]
It seems that any variables that  have a "standard key" for their name break the parser. 

See dijit/_PaletteMixin for an example. Here we have a variable named "summary" that breaks the parser with : TypeError: Cannot read property 'type' of undefined

```
// summary: String
//      Localized summary for the palette table
summary: '',
```

I also tested it with 'example' and that also failed (although this file is the only live example I have come across) . Changing the name to anything else works fine.

**Comment by wkeese** [comment]
FYI this is breaking parsing of three files in dojo:
- dijit/_PaletteMixin.js
- dojox/grid/enhanced/plugins/Pagination.js
- dojox/image/FlickrBadge.js
