### ISSUE TITLE
make js-doc-parse  runnable with dojo installed elsewhere than in ./dojo

### ISSUE THREAD

**Issue by cjolif** [csnover/js-doc-parse#34]
If I want to distribute js-doc-parse with a dojo version I don't want dojo to be a child directory of js-doc-parse. I want  for example js-doc-pase in the dojo/utils directory. There should be a way to specify where to load dojo when running the tool.

**Comment by csnover** [comment]
I don’t plan to support this now or possibly ever. You can load the parser using your own bootstrap script if you need to redirect dojo and register package paths differently and it should work, but I do not expect this to be a common case.
