### ISSUE TITLE
Decide how to handle djConfig

### ISSUE THREAD

**Issue by ttrenka** [csnover/js-doc-parse#41]
In previous iterations of the parser/viewer, djConfig was handled as a "special case" object in an attempt to make it clear what various configuration options are available to a user.  The problem with it was that lots of various configuration options were attached to different references of the same object; for instance, there may have been "isDebug" attached to djConfig, while other options may have been attached to `dojo.config` later on in code--which itself was just a reference to djConfig (if it existed).

I'm not sure how we should handle djConfig et al, but it will be a definite requirement for viewing 1.8+ API documentation.  This ticket is here to keep a reference for that discussion/solution.

**Comment by csnover** [comment]
I don’t think it really matters. There are other resources that describe how to install and configure the toolkit in the tutorials series.

**Comment by wkeese** [comment]
In the AMD world, djConfig has been replaced by the dojo/_base/config module (see http://livedocs.dojotoolkit.org/dojo/_base/config), although unfortunately some code is still accessing it through dojo/_base/kernel::config... but anyway I think the dojo/_base/config module page would list of configuration options.

I updated that module to list all the definitions of dojo core and dijit flags, and filed http://bugs.dojotoolkit.org/ticket/15519 for dojox/mobile.   Not sure what other flags exist.

Currently, http://livedocs.dojotoolkit.org/dojo/_base/config links to http://dojotoolkit.org/api/dojo/config but that should be changed to link to dojo/_base/config once the new doc viewer is up and running.

So I don't think there's any doc parser issue, we can probably close this, right?

**Comment by ttrenka** [comment]
I'll deal with it in the doc viewer then, and close the issue. There are some dojox projects that look for things within that particular object; we'll deal with it when the time comes.
