### ISSUE TITLE
HTML in markdown not properly encoded

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#46]
dojo/parser.js has this code:

``` javascript
// scripts: DomNode[]?
//      Array of <script type="dojo/*"> DOMNodes.  If not specified, will search for <script> tags inside node.
```

I think the literal "<script..." is valid syntax since this is markdown, not HTML.    However, the parser doesn't double-encode the value, so we end up with

``` xml
<summary>&lt;p>Array of &lt;script type=&quot;dojo/*&quot;> DOMNodes.
```

which means the value of the summary node evaluates to

``` xml
<p>Array of <script type="dojo/*"> DOMNodes. ...
```

rather than what we want:

``` xml
<p>Array of &lt;script type="dojo/*"&gt; DOMNodes. ...
```

cc @kitsonk

**Comment by csnover** [comment]
Yes this is true; Markdown is actually a weird superset of HTML so if you’re not putting your HTML `<in code blocks>` it will be treated as HTML. I can enable `sanitize` in the Markdown parser if you think that’s the right thing to do here though I don’t know _exactly_ what that means at the moment (i.e. whether it deletes the tags or just encodes them).

**Comment by wkeese** [comment]
Oh I see, OK thanks, I'll just fix the parser code, that seems safer.
