### ISSUE TITLE
Wrapping <pre> in <code> unecessary

### ISSUE THREAD

**Issue by kitsonk** [csnover/js-doc-parse#55]
It seems that for examples, the js-doc-parse is wrapping examples in both `<pre>` and `<code>`.  This is causing spacing issues in the API viewer, which can be somewhat offset by CSS styling, but it would be very handy that if something is already in a `<pre>` block, that it doesn't also get `<code>` wrapped.

**Comment by wkeese** [comment]
I'm actually searching for `<pre><code>` in the API viewer as a way to turn on the syntax highlighting, so I replace `<pre><code>` with something else.   You must be looking at examples w/out the syntax highlighting... what's an example of what you are looking at?

**Comment by kitsonk** [comment]
If you look at dojo/query for example in the API viewer.  It is the Usage
blocks.  Before I checked in the CSS, you saw the yellow code block, but
the text was gray lines with a border.

So maybe you aren't turning on the highlighting except for examples?  Also,
which is a separate issue, the code uses some bullet markdown which the
js-doc-parse thinks is code.

I can standardise rstwiki to also modify the <pre><code> as well, but it
does seem a bit odd, in that we really should have just <pre>.

I can see that the Examples are coming across the wire fine, which means
there is something odd with the highlighter/CSS interaction that I need to
override, because the spacing between the lines has some issues.

On 2 July 2012 01:40, Bill Keese <
reply@reply.github.com

**Comment by wkeese** [comment]
Ah I see.

I just fixed the problem with the lists appearing as code (see [[29103]](http://bugs.dojotoolkit.org/changeset/29103/dojo)).

And yes, the syntax highlighting is only turned on for examples, perhaps it should be done everywhere?

Regarding your claim that "wrapping `<pre>` in `<code>` is unnecessary", the [HTML5 spec](http://www.w3.org/TR/html5/the-pre-element.html#the-pre-element) says that you _should_ use the `<pre><code>` combo.   (I learned this from the [StackOverflow entry](http://stackoverflow.com/questions/4611591/code-vs-pre-vs-samp-for-inline-and-block-code-snippets).)

**Comment by kitsonk** [comment]
Ah, ok!  I CSS'ed the interference away on the API viewer, so if it is the proper way to do it, then so be it.
