### ISSUE TITLE
return query(...) // dojo/NodeList not working

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#58]
See for example dijit/form/MultiSelect :: getSelected():

```
getSelected: function(){
    // summary:
    //      Access the NodeList of the selected options directly
    return query("option",this.containerNode).filter(function(n){
        return n.selected; // Boolean
    }); // dojo/NodeList
},
```

The XML output is listing the type as undefined:

``` xml
<method name="getSelected" scope="prototype" type="function" from="dijit/form/MultiSelect">
<parameters/>
<return-types>
<return-type type="undefined"/>
</return-types>
<summary>
<p>Access the NodeList of the selected options directly</p>
</summary>
</method>
```

**Comment by csnover** [comment]
This is expected. See “Return Value” section at http://dojotoolkit.org/community/styleGuide#Documentation.

**Comment by wkeese** [comment]
That page is just talking about the description of the return value, not the doc-hint for the type.

But anyway this looks like a dup of #24... that doc-hints for return types aren't working at all.
