### ISSUE TITLE
comment on line declaring export variable masks summary

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#66]
dojo/_base/array.js had:

``` javascript

var array = {                        // the export object
    // summary:
    //      The Javascript v1.6 array extensions.
    ...
};
...

return array;
```

Yet for some reason the summary didn't end up in the details.xml file.

Same for dojo/_base/unload.

**Comment by csnover** [comment]
what’s with the `// the export object` comment on the previous line? i wouldn’t be surprised if that was causing the dojodoc processor to think that it’s not a dojodoc block and to ignore it.

**Comment by wkeese** [comment]
Cool, getting rid of the comment works around the problem.    There was no special purpose to the comment, just an explanation of what the `array` variable was.

**Comment by csnover** [comment]
I don’t think this is really a bug in the parser, it’s intentional, designed to avoid when someone does something like:

``` javascript:
// blah blah blah, blah blah
// blah blah, something etc.
// TODO: Finish this
```
