### ISSUE TITLE
dijit/_WidgetBase missing attributes

### ISSUE THREAD

**Issue by wkeese** [csnover/js-doc-parse#7]
Seems that "open" and "duration" aren't showing up in the doc for dijit/_WidgetBase:

./parse.sh ../trunk/dijit/_WidgetBase.js 2>warnings.txt |sed -n '/<javascript/,$p' > WidgetBase.xml

**Comment by csnover** [comment]
I don’t understand. `open` and `duration` aren’t properties on _WidgetBase or any of its parents, so they don’t show up there. Where do you think these would be coming from?

**Comment by wkeese** [comment]
Sounds like I confused Dialog.js with WidgetBase.js. (I was looking at both
of them at the same time.).  I'll double check later.

**Comment by csnover** [comment]
OK. open and duration are showing up on dijit/Dialog just fine after some changes I made earlier this evening so let me know what you are experiencing.

**Comment by wkeese** [comment]
Yup, it's working for me too, ignore this ticket.
