### ISSUE TITLE
Ubuntu/Canonical process.execPath = /usr/bin/nodejs

### ISSUE THREAD

**Issue by lbod** [csnover/js-doc-parse#72]
Can the dojo submodule be upgraded to 1.8.3 please?
This fixes the stupid exec location problem on ubuntu where js-doc-parse will fail unless you've make installed it via debian etc.
e.g. execPath: "/usr/bin/nodejs"

1.8.3 works fine for me

**Comment by csnover** [comment]
Yeah, fixes means fixes, GitHub.
