### ISSUE TITLE
ERR: TypeError: Object true has no method 'match'

### ISSUE THREAD

**Issue by shioyang** [csnover/js-doc-parse#86]
The following error occurs, when I issued "parse.bat config=./config.js".
How can I resolve this problem? I would appreciate if you could give some advice.

> C:\LocalProgramFiles\js-doc-parse>parse.bat config=./config.js
> ERR:  TypeError: Object true has no method 'match'
>     at getModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1010:16)
>     at contextRequire (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:767:17)
>     at result (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:808:13)
>     at C:/LocalProgramFiles/js-doc-parse/lib/env.js:250:2
>     at runFactory (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1094:43)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1223:5)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1214:12)
>     at execModule (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1214:12)
>     at C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1258:6
>     at guardCheckComplete (C:\LocalProgramFiles\js-doc-parse\dojo\dojo.js:1238:5)

I did on command prompt with Admin:
        $ git clone --recursive https://github.com/csnover/js-doc-parse.git
        $ cd js-doc-parse
        $ [Edit config.js: configure basePath and replace \ to \\]
        $ parse.bat config=./config.js

Env:
Win7 64 (UAC disabled)

**Comment by csnover** [comment]
The bug tracker is not a support forum. Please post support requests to the [dojo-interest mailing list](http://mail.dojotoolkit.org/mailman/listinfo/dojo-interest).

**Comment by shioyang** [comment]
Hi, thank you for your reply.
ok, I will post this issue to the mailing list.

**Comment by jk1420** [comment]
hi shioyang, I has the same problem when i run the parse.bat on win7 64. And I find you had post this issue to the mailing list, i want to know are you had get the reply, and can you reply it to me ? I would appreciate if you could reply it.

**Comment by shioyang** [comment]
Hi, jk1420:
Unfortunately, I hadn't received any replies to resolve the issue.
I had tried to search and analyze clues and causes of the issue, but I couldn't. So, I had given up...

**Comment by jk1420** [comment]
Hi, shioyang:
Thx for your reply, may be I wil try setup linux on a vitual machine to go
on.

2013/7/20 shioyang notifications@github.com

**Comment by jaypieybut** [comment]
Hi jk1420, we're you able to fix it in running on linux virtual machine?
